"""Core package for the image registration internship project."""

from .benchmark import (
    BenchmarkCasePlan,
    benchmark_manifest_fingerprint,
    build_case_plan,
    sample_benchmark_ground_truth,
    validate_benchmark_records,
    validate_integrated_benchmark_config,
)
from .config import build_transform, config_hash, load_config, with_defaults
from .conventions import (
    ANGLE_UNIT,
    COORDINATE_ORDER,
    POSITIVE_ROTATION_DIRECTION,
    STORED_TRANSFORM_DIRECTION,
)
from .datasets import (
    DatasetValidationReport,
    build_raster_source_record,
    load_dataset_manifest,
    sha256_file,
    validate_dataset_manifest,
    write_dataset_manifest,
)
from .degradations import (
    DegradationResult,
    adjust_contrast,
    adjust_gamma,
    apply_degradation,
    gaussian_blur as apply_gaussian_blur,
    gaussian_noise,
    illumination_gradient,
    impulse_noise,
    rectangular_occlusion,
)
from .difficulty import (
    DifficultySample,
    sample_similarity_difficulty,
    validate_difficulty_tiers,
)
from .evaluation import (
    evaluate_pair,
    mean_absolute_error,
    mean_squared_error,
    normalized_cross_correlation,
    structural_similarity,
)
from .io import LoadedImage, load_image, validate_image_pair
from .medical import MedicalImageMetadata, read_medical_image_metadata
from .pipeline import ExperimentResult, run_experiment
from .multimodal import (
    MultimodalResult,
    apply_multimodal_mapping,
    edge_emphasized_representation,
    histogram_remap,
    intensity_inversion,
    modality_specific_noise,
    multiplicative_bias_field,
    nonlinear_gamma_mapping,
)
from .overlap import (
    apply_field_of_view,
    combine_valid_masks,
    overlap_fraction,
    overlap_mask_in_fixed_space,
    rectangular_field_of_view_mask,
    transformed_support_mask,
)
from .preprocessing import (
    clip_percentiles,
    crop_to_mask,
    gaussian_smooth,
    preprocess_image,
    resize_image,
    robust_normalize,
    to_grayscale,
)
from .transforms import (
    affine_matrix,
    apply_transform,
    compose_transforms,
    from_homogeneous,
    identity_matrix,
    invert_transform,
    rigid_matrix,
    rotation_matrix,
    similarity_matrix,
    to_homogeneous,
    translation_matrix,
)
from .registration import RegistrationMethod, RegistrationResult
from .rire import (
    RireHeader,
    find_rire_volume_files,
    parse_rire_header,
    read_rire_volume,
)
from .synthetic import (
    GroundTruthTransform,
    SyntheticPair,
    control_point_round_trip_error,
    default_control_points,
    generate_synthetic_pair,
    image_center,
    sample_ground_truth_transform,
)
from .visualization import (
    absolute_difference,
    alpha_overlay,
    checkerboard,
    save_comparison_figure,
    save_grayscale_image,
    save_intensity_histogram,
    save_joint_histogram,
)
from .warping import warp_image, warp_mask

__all__ = [
    "BenchmarkCasePlan",
    "benchmark_manifest_fingerprint",
    "build_case_plan",
    "sample_benchmark_ground_truth",
    "validate_benchmark_records",
    "validate_integrated_benchmark_config",
    "DatasetValidationReport",
    "RireHeader",
    "build_raster_source_record",
    "find_rire_volume_files",
    "load_dataset_manifest",
    "parse_rire_header",
    "read_rire_volume",
    "read_medical_image_metadata",
    "sha256_file",
    "validate_dataset_manifest",
    "write_dataset_manifest",
    "DifficultySample",
    "MultimodalResult",
    "MedicalImageMetadata",
    "apply_multimodal_mapping",
    "edge_emphasized_representation",
    "histogram_remap",
    "intensity_inversion",
    "modality_specific_noise",
    "multiplicative_bias_field",
    "nonlinear_gamma_mapping",
    "sample_similarity_difficulty",
    "save_intensity_histogram",
    "save_joint_histogram",
    "validate_difficulty_tiers",
    "ANGLE_UNIT",
    "DegradationResult",
    "ExperimentResult",
    "RegistrationMethod",
    "RegistrationResult",
    "GroundTruthTransform",
    "SyntheticPair",
    "COORDINATE_ORDER",
    "POSITIVE_ROTATION_DIRECTION",
    "STORED_TRANSFORM_DIRECTION",
    "LoadedImage",
    "absolute_difference",
    "adjust_contrast",
    "adjust_gamma",
    "build_transform",
    "config_hash",
    "affine_matrix",
    "alpha_overlay",
    "apply_degradation",
    "apply_field_of_view",
    "apply_gaussian_blur",
    "apply_transform",
    "checkerboard",
    "clip_percentiles",
    "combine_valid_masks",
    "compose_transforms",
    "control_point_round_trip_error",
    "crop_to_mask",
    "default_control_points",
    "evaluate_pair",
    "from_homogeneous",
    "generate_synthetic_pair",
    "gaussian_smooth",
    "gaussian_noise",
    "identity_matrix",
    "illumination_gradient",
    "image_center",
    "impulse_noise",
    "invert_transform",
    "load_config",
    "load_image",
    "mean_absolute_error",
    "mean_squared_error",
    "normalized_cross_correlation",
    "overlap_fraction",
    "overlap_mask_in_fixed_space",
    "preprocess_image",
    "rectangular_field_of_view_mask",
    "rectangular_occlusion",
    "resize_image",
    "rigid_matrix",
    "robust_normalize",
    "run_experiment",
    "rotation_matrix",
    "save_comparison_figure",
    "save_grayscale_image",
    "sample_ground_truth_transform",
    "similarity_matrix",
    "structural_similarity",
    "to_grayscale",
    "to_homogeneous",
    "translation_matrix",
    "transformed_support_mask",
    "validate_image_pair",
    "warp_image",
    "warp_mask",
    "with_defaults",
]
